//
// Generated file, do not edit! Created by opp_msgc 4.5 from modules/messages/WaveShortMessage.msg.
//

#ifndef _WAVESHORTMESSAGE_M_H_
#define _WAVESHORTMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Coord.h"
#include "CarMove.h"
// }}



/**
 * Class generated from <tt>modules/messages/WaveShortMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet WaveShortMessage{
 *     
 * 	int wsmVersion = 0;
 * 	
 * 	int securityType = 0;
 * 	
 * 	int channelNumber;
 * 	
 * 	int dataRate = 1;
 * 	
 * 	int priority = 3;
 * 	
 * 	int psid = 0;
 * 	
 * 	string psc = "Service with some Data";
 * 	
 * 	int wsmLength;
 * 	
 * 	string wsmData = "Some Data";
 * 
 * 	int senderAddress = 0;
 * 	int recipientAddress = -1;
 * 	int serial = 0;
 * 	Coord senderPos;
 * 	simtime_t timestamp = 0;
 * 	Coord direction;
 * 	double speed = 0;
 * 	
 * 	CarMove carlist[10] = 0;
 * 	
 * 	
 * 	
 * 	
 * 	
 * 	int hopLimit = 1;
 * 	
 * 	
 * 	int flag = 0;
 * 	
 * 	
 * 	int originalAddress = -1;
 * 	
 * 	
 * 	int userPriority = 0;
 * 	
 * 	
 * 	int nextForwardAddress; 
 * 	
 * 	
 * 	int psid2 = 0;
 * 	int flag2 = 0;
 * 	int userPriority2 = 0;
 * 	int sch2 = 0;
 * 	int dst2 = -1;
 * 	int hopLimit2 = 1;
 * 	simtime_t timeStamp2 = 0;
 * }
 * </pre>
 */
class WaveShortMessage : public ::cPacket
{
  protected:
    int wsmVersion_var;
    int securityType_var;
    int channelNumber_var;
    int dataRate_var;
    int priority_var;
    int psid_var;
    opp_string psc_var;
    int wsmLength_var;
    opp_string wsmData_var;
    int senderAddress_var;
    int recipientAddress_var;
    int serial_var;
    Coord senderPos_var;
    simtime_t timestamp_var;
    Coord direction_var;
    double speed_var;
    CarMove carlist_var[10];
    int hopLimit_var;
    int flag_var;
    int originalAddress_var;
    int userPriority_var;
    int nextForwardAddress_var;
    int psid2_var;
    int flag2_var;
    int userPriority2_var;
    int sch2_var;
    int dst2_var;
    int hopLimit2_var;
    simtime_t timeStamp2_var;

  private:
    void copy(const WaveShortMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WaveShortMessage&);

  public:
    WaveShortMessage(const char *name=NULL, int kind=0);
    WaveShortMessage(const WaveShortMessage& other);
    virtual ~WaveShortMessage();
    WaveShortMessage& operator=(const WaveShortMessage& other);
    virtual WaveShortMessage *dup() const {return new WaveShortMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getWsmVersion() const;
    virtual void setWsmVersion(int wsmVersion);
    virtual int getSecurityType() const;
    virtual void setSecurityType(int securityType);
    virtual int getChannelNumber() const;
    virtual void setChannelNumber(int channelNumber);
    virtual int getDataRate() const;
    virtual void setDataRate(int dataRate);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual int getPsid() const;
    virtual void setPsid(int psid);
    virtual const char * getPsc() const;
    virtual void setPsc(const char * psc);
    virtual int getWsmLength() const;
    virtual void setWsmLength(int wsmLength);
    virtual const char * getWsmData() const;
    virtual void setWsmData(const char * wsmData);
    virtual int getSenderAddress() const;
    virtual void setSenderAddress(int senderAddress);
    virtual int getRecipientAddress() const;
    virtual void setRecipientAddress(int recipientAddress);
    virtual int getSerial() const;
    virtual void setSerial(int serial);
    virtual Coord& getSenderPos();
    virtual const Coord& getSenderPos() const {return const_cast<WaveShortMessage*>(this)->getSenderPos();}
    virtual void setSenderPos(const Coord& senderPos);
    virtual simtime_t getTimestamp() const;
    virtual void setTimestamp(simtime_t timestamp);
    virtual Coord& getDirection();
    virtual const Coord& getDirection() const {return const_cast<WaveShortMessage*>(this)->getDirection();}
    virtual void setDirection(const Coord& direction);
    virtual double getSpeed() const;
    virtual void setSpeed(double speed);
    virtual unsigned int getCarlistArraySize() const;
    virtual CarMove& getCarlist(unsigned int k);
    virtual const CarMove& getCarlist(unsigned int k) const {return const_cast<WaveShortMessage*>(this)->getCarlist(k);}
    virtual void setCarlist(unsigned int k, const CarMove& carlist);
    virtual int getHopLimit() const;
    virtual void setHopLimit(int hopLimit);
    virtual int getFlag() const;
    virtual void setFlag(int flag);
    virtual int getOriginalAddress() const;
    virtual void setOriginalAddress(int originalAddress);
    virtual int getUserPriority() const;
    virtual void setUserPriority(int userPriority);
    virtual int getNextForwardAddress() const;
    virtual void setNextForwardAddress(int nextForwardAddress);
    virtual int getPsid2() const;
    virtual void setPsid2(int psid2);
    virtual int getFlag2() const;
    virtual void setFlag2(int flag2);
    virtual int getUserPriority2() const;
    virtual void setUserPriority2(int userPriority2);
    virtual int getSch2() const;
    virtual void setSch2(int sch2);
    virtual int getDst2() const;
    virtual void setDst2(int dst2);
    virtual int getHopLimit2() const;
    virtual void setHopLimit2(int hopLimit2);
    virtual simtime_t getTimeStamp2() const;
    virtual void setTimeStamp2(simtime_t timeStamp2);
};

inline void doPacking(cCommBuffer *b, WaveShortMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WaveShortMessage& obj) {obj.parsimUnpack(b);}


#endif // _WAVESHORTMESSAGE_M_H_
